prose
prose-p:content
prose-p:my-0
prose-headings:mt-em
prose-headings:mb-0
prose-h2:h2
prose-h3:h3
prose-h4:h4
prose-ul:my-0
prose-ol:my-0
prose-ul:space-y-em
prose-ol:space-y-em
prose-li:my-0
prose-blockquote:my-0
prose-blockquote:border-primary-700
prose-blockquote:pl-7
prose-blockquote:not-italic
prose-li:marker:text-primary
prose-pre:whitespace-pre-wrap
prose-pre:my-0
prose-strong:text-neutral-900
prose-code:text-rose
max-w-none
